// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: chat.proto

#include "chat.pb.h"
#include "chat.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>
namespace chat {

static const char* ChatService_method_names[] = {
  "/chat.ChatService/SendMessage",
  "/chat.ChatService/ShowMessage",
};

std::unique_ptr< ChatService::Stub> ChatService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< ChatService::Stub> stub(new ChatService::Stub(channel, options));
  return stub;
}

ChatService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_SendMessage_(ChatService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ShowMessage_(ChatService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  {}

::grpc::Status ChatService::Stub::SendMessage(::grpc::ClientContext* context, const ::chat::ChatMsg& request, ::chat::ChatMsg* response) {
  return ::grpc::internal::BlockingUnaryCall< ::chat::ChatMsg, ::chat::ChatMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SendMessage_, context, request, response);
}

void ChatService::Stub::async::SendMessage(::grpc::ClientContext* context, const ::chat::ChatMsg* request, ::chat::ChatMsg* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::chat::ChatMsg, ::chat::ChatMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendMessage_, context, request, response, std::move(f));
}

void ChatService::Stub::async::SendMessage(::grpc::ClientContext* context, const ::chat::ChatMsg* request, ::chat::ChatMsg* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendMessage_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::chat::ChatMsg>* ChatService::Stub::PrepareAsyncSendMessageRaw(::grpc::ClientContext* context, const ::chat::ChatMsg& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::chat::ChatMsg, ::chat::ChatMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SendMessage_, context, request);
}

::grpc::ClientAsyncResponseReader< ::chat::ChatMsg>* ChatService::Stub::AsyncSendMessageRaw(::grpc::ClientContext* context, const ::chat::ChatMsg& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSendMessageRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::ClientReader< ::chat::ChatMsg>* ChatService::Stub::ShowMessageRaw(::grpc::ClientContext* context, const ::chat::ChatMsg& request) {
  return ::grpc::internal::ClientReaderFactory< ::chat::ChatMsg>::Create(channel_.get(), rpcmethod_ShowMessage_, context, request);
}

void ChatService::Stub::async::ShowMessage(::grpc::ClientContext* context, const ::chat::ChatMsg* request, ::grpc::ClientReadReactor< ::chat::ChatMsg>* reactor) {
  ::grpc::internal::ClientCallbackReaderFactory< ::chat::ChatMsg>::Create(stub_->channel_.get(), stub_->rpcmethod_ShowMessage_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::chat::ChatMsg>* ChatService::Stub::AsyncShowMessageRaw(::grpc::ClientContext* context, const ::chat::ChatMsg& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::chat::ChatMsg>::Create(channel_.get(), cq, rpcmethod_ShowMessage_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::chat::ChatMsg>* ChatService::Stub::PrepareAsyncShowMessageRaw(::grpc::ClientContext* context, const ::chat::ChatMsg& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::chat::ChatMsg>::Create(channel_.get(), cq, rpcmethod_ShowMessage_, context, request, false, nullptr);
}

ChatService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ChatService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ChatService::Service, ::chat::ChatMsg, ::chat::ChatMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ChatService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::chat::ChatMsg* req,
             ::chat::ChatMsg* resp) {
               return service->SendMessage(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ChatService_method_names[1],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< ChatService::Service, ::chat::ChatMsg, ::chat::ChatMsg>(
          [](ChatService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::chat::ChatMsg* req,
             ::grpc::ServerWriter<::chat::ChatMsg>* writer) {
               return service->ShowMessage(ctx, req, writer);
             }, this)));
}

ChatService::Service::~Service() {
}

::grpc::Status ChatService::Service::SendMessage(::grpc::ServerContext* context, const ::chat::ChatMsg* request, ::chat::ChatMsg* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ChatService::Service::ShowMessage(::grpc::ServerContext* context, const ::chat::ChatMsg* request, ::grpc::ServerWriter< ::chat::ChatMsg>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace chat
#include <grpcpp/ports_undef.inc>

